"""A case page may not contradict the code it documents.

The case pages were authored while six generators still had no truth node. Adding the truths did not
touch the prose, so pages went on saying "NO, no truth_node is defined" for cases that had just
acquired a verified one. Documentation that contradicts the artifact is worse than documentation
that is missing: a reader has no way to tell which one is lying, and both look authoritative.

The mechanical rows are generated by `scripts/sync_case_doc_truth_rows.py`. This test is the gate:
it recomputes them and fails when a page has drifted, naming the script that fixes it.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs" / "cases"

sys.path.insert(0, str(ROOT / "scripts"))
from sync_case_doc_truth_rows import truth_state  # noqa: E402

PAGES = sorted(DOCS.glob("*.md"))


def _case_id(text: str) -> str | None:
    match = re.search(r"^\| Case id \| `([^`]+)` \|$", text, re.M)
    return match.group(1) if match else None


@pytest.mark.parametrize("path", PAGES, ids=lambda p: p.name)
def test_page_truth_row_matches_the_code(path: Path) -> None:
    text = path.read_text(encoding="utf-8")
    case_id = _case_id(text)
    assert case_id, f"{path.name} has no machine-readable case id row"

    has_truth, regime, _ = truth_state(case_id)

    truth_row = re.search(r"^\| Machine-comparable truth \| (\w+),", text, re.M)
    assert truth_row, f"{path.name} has no machine-comparable truth row"
    stated = truth_row.group(1) == "YES"
    assert stated == has_truth, (
        f"{path.name} says machine-comparable truth {truth_row.group(1)} but the code says "
        f"{'YES' if has_truth else 'NO'}. Run scripts/sync_case_doc_truth_rows.py."
    )

    regime_row = re.search(r"^\| Recovery regime \| `([^`]+)` \|$", text, re.M)
    assert regime_row, f"{path.name} has no recovery regime row"
    assert regime_row.group(1) == regime, (
        f"{path.name} says regime {regime_row.group(1)} but the code says {regime}. "
        "Run scripts/sync_case_doc_truth_rows.py."
    )


def test_the_sync_script_is_idempotent() -> None:
    """Running the generator twice must change nothing the second time.

    A generator that keeps rewriting its own output would make this gate permanently red and train
    everyone to ignore it.
    """
    script = ROOT / "scripts" / "sync_case_doc_truth_rows.py"
    first = subprocess.run(
        [sys.executable, str(script)], capture_output=True, text=True, cwd=ROOT, check=True
    )
    assert "synced 0 case pages" in first.stdout or "none" in first.stdout, (
        f"the sync script still had work to do: {first.stdout.strip()}"
    )


def test_every_case_has_a_page() -> None:
    """The wiki promises one page per case; a missing page is a promise the index breaks."""
    sys.path.insert(0, str(ROOT / "data-pipeline"))
    from symlab.cases.registry import list_cases

    documented = {_case_id(p.read_text(encoding="utf-8")) for p in PAGES}
    missing = sorted(c.id for c in list_cases() if c.id not in documented)
    assert not missing, f"registry cases with no page in docs/cases/: {missing}"
